spring:
  data:
    mongodb:
      uri: ${DB_USER_CONNECTION}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

  jackson:
    time-zone: Asia/Kolkata

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info, prometheus

app:
  name: hello user bro

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#keycloaak
keycloak:
  server-url: http://127.0.0.1:8443
  realm: master

  endpoints:
    token: ${keycloak.server-url}/realms/master/protocol/openid-connect/token
    users: ${keycloak.server-url}/admin/realms/${keycloak.realm}/users

  admin:
    client-id: ecom-app-client
    client-secret: vLhakdaJNAikmRXu6NBJ1tEFTEflksAR
    grant-type: password
    username: admin_new
    password: admin

  connection:
    connect-timeout: 5000
    read-timeout: 5000
