#spring:
#  application:
#    name: order
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#  sql:
#    init:
#      mode: never
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jackson:
#    time-zone: Asia/Kolkata
spring:
  application:
    name: order
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order?currentSchema=public
#    username: postgres
#    password: lenin
#    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: never
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Asia/Kolkata
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  jackson:
#    time-zone: Asia/Kolkata
#
#server:
#  port: 8083

  config:
    import: optional:configserver:http://localhost:8888